name: ci-reusable
on:
  workflow_call:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-ci
        with:
          node-version: "20"
          working-directory: "frontend"
      - run: npm run lint --if-present
        working-directory: frontend
      - run: npm test --if-present
        working-directory: frontend
      - run: npm run build
        working-directory: frontend

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-ci
        with:
          node-version: "20"
          working-directory: "backend"
      - run: npm run lint --if-present
        working-directory: backend
      - run: npm test --if-present
        working-directory: backend
      - run: npm run build
        working-directory: backend
