name: ci-reusable
on:
  workflow_call:

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-ci
        with:
          node-version: "20"
      - run: npm run lint --if-present
      - run: npm test --if-present
      - run: npm run build

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-ci
        with:
          node-version: "20"
      - run: npm run lint --if-present
      - run: npm test --if-present
      - run: npm run build
